### ISSUE TITLE
Make CMIS adapter Django 3.2 compatible

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/cmis-adapter#63]
Currently CMIS-adapter is pinned to < Django 3.0, but 2.2 is end of life in April this year and this library currently blocks upgrading Open Zaak to 3.2 LTS.

**Tasks**

- [x] Update the `tox.ini` envlist to support the following matrix of versions
    - Python 3.7 - Django 2.2
    - Python 3.8 - Django 2.2
    - Python 3.7 - Django 3.2
    - Python 3.8 - Django 2.2
- [x] Update the Github CI workflow to support the same matrix
- [x] Make the necessary changes to the package to support Django 3.2
- [x] Update the package metadata to correctly reflect the supported versions
- [x] Extra: see if we can add Python 3.9 and Python 3.10 support

**Comment by ahmadpoorgholam** [comment]
after more investigation we need to update the VNG adapter first here is the ticket for it https://github.com/VNG-Realisatie/vng-api-common/issues/190
